import TaskApp from '@/components/task'
import Head from 'next/head'

export default function Home() {
  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TaskApp />
      </main>
    </>
  )
}
